### ISSUE TITLE
Releasing synthetic captions?

### ISSUE THREAD

**Issue by vishaal27** [deepglint/ALIP#3]
Hey, thanks for your great work! I was interested in whether you would be able to release the synthetic captions you used for training ALIP? Thanks!

**Comment by kaichengyang0828** [comment]
We pack the text tokens and image data to the rec file and it is too big(600GB), all the captions are generated by using [OFA](https://github.com/OFA-Sys/OFA) repo, you can just generate it using the [script](https://github.com/OFA-Sys/OFA/blob/main/run_scripts/caption/evaluate_caption_base.sh)!
