### ISSUE TITLE
请问一个图像非常复杂，前景和背景里面的描述都要标注出来吗？我看MUGE Flickr30k这些都是只标最显著的目标

### ISSUE THREAD

**Issue by ctgushiwei** [deepglint/ALIP#4]

**Comment by kaichengyang0828** [comment]
不好意思，你可以给出更详细的问题描述嘛？我暂时没有明白你是想问预训练数据caption还是下游测试Flickr30k的caption

**Comment by ctgushiwei** [comment]
在自己的数据集上进行微调，假如是一张图上有很多目标，在标注文本时是不是都要描述出来？还是仅仅描述最显著的目标。

**Comment by kaichengyang0828** [comment]
如果你想进行跨模态对比学习的话，理论上越详细越好，但是请注意CLIP text tokenizer限制了77长度(可以考虑设置更大的token sequence lenth)，希望对你有帮助！

**Comment by ctgushiwei** [comment]
举个具体例子，假如现在检索小米SU7这款车效果很差，需要进行微调，那么微调时加多少数据，或者怎么加微调数据可以让检索小米SU7效果较好呢？有没有一些经验

**Comment by kaichengyang0828** [comment]
这个不太好量化（和要学习的概念的难度以及你理想的性能直接相关），下述意见供参考：
1、添加文本描述的时候要突出SU7的特点（尽可能多的增加detailed information），指引模型更好的将SU7这个概念和图片中汽车的特点在学习的过程中关联起来
2、由于图片可能数量有限，可以考虑一张图对应多个文本，通过text augmentation来进行学习(当然图像也可以进行augmentation)
3、ALIP仅在YFCC15M上进行的训练，因此模型能力和泛化性有限，考虑使用在更大规模数据上预训练的模型(例如EVA-CLIP)
希望对你有帮助！

**Comment by ctgushiwei** [comment]
非常感谢您详尽的回答。还想请问下，还是以微调小米SU7为例，请问除了加小米SU7的图文描述数据，请问是否需要加负样本，比如其他类型汽车进行对比学习

**Comment by kaichengyang0828** [comment]
当然可以，实际上你的目标就是让模型学习到不同品牌的汽车细粒度的差异

**Comment by ctgushiwei** [comment]
大佬，还有个小问题，假如训练数据图像都是小图（比如640*380，640*480）这些图像数据，但是实际场景都是2560*1440这类图像，会对检索精度有影响吗？影响有多大呢

**Comment by kaichengyang0828** [comment]
直接的方法：可以考虑使用更大分辨率的数据通过插值来训练支持更大分辨率的预训练模型，请参考CLIP- L14@336的训练方式.
间接的方法：可以考虑在实际场景pipeline上加入一些检测的模型基于检测框进行crop然后再进行检索.

**Comment by kaichengyang0828** [comment]
感谢您对ALIP的关注，该issue即将被关闭，如有新的与ALIP相关的问题请另提issue！
